import { SkillType } from "@lib/types";
import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiReact,
  SiJava,
  SiSpring,
  SiMysql,
  SiMongodb,
  SiOracle,
  SiGooglecloud,
  SiGit,
  SiGithub,
  SiGitlab,
  SiBitbucket,
  SiIntellijidea,
  SiEclipseide,
  SiVisualstudiocode,
  SiMaven,
  SiGradle,
  SiJira,
  SiBootstrap,
} from "react-icons/si";

const skills: SkillType[] = [
  { name: "Java", Icon: SiJava },
  { name: "Spring (Boot)", Icon: SiSpring },
  { name: "REST APIs", Icon: SiJava },
  { name: "Microservices", Icon: SiSpring },
  { name: "JSP", Icon: SiJava },
  { name: "JavaScript", Icon: SiJavascript },
  { name: "ReactJS", Icon: SiReact },
  { name: "HTML", Icon: SiHtml5 },
  { name: "CSS", Icon: SiCss3 },
  { name: "Bootstrap", Icon: SiBootstrap },
  { name: "MySQL", Icon: SiMysql },
  { name: "MongoDB", Icon: SiMongodb },
  { name: "Oracle", Icon: SiOracle },
  { name: "GCP", Icon: SiGooglecloud },
  { name: "Git", Icon: SiGit },
  { name: "GitHub", Icon: SiGithub },
  { name: "GitLab", Icon: SiGitlab },
  { name: "Bitbucket", Icon: SiBitbucket },
  { name: "IntelliJ IDEA", Icon: SiIntellijidea },
  { name: "Eclipse", Icon: SiEclipseide },
  { name: "VS Code", Icon: SiVisualstudiocode },
  { name: "Maven", Icon: SiMaven },
  { name: "Gradle", Icon: SiGradle },
  { name: "Jira", Icon: SiJira },
];

export default skills;
